sudo: required

services:
    - docker

before_install:
    - docker build  -f ./client/Dockerfile.dev -t dpolist/react-test ./client

script:
    - docker run -e CI=true dpolist/react-test npm test

after_success:
    - docker build -t dpolist/multi-client ./client
    - docker build -t dpolist/multi-nginx ./nginx
    - docker build -t dpolist/multi-server ./server
    - docker build -t dpolist/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push dpolist/multi-client
    - docker push dpolist/multi-nginx
    - docker push dpolist/multi-server
    - docker push dpolist/multi-worker
